/**
 * MiniMax's system voices, from its own list (platform.minimax.cn/docs/faq/system-voice-id,
 * read 2026-09-29). Each id names the language it speaks, and a system voice speaks only that
 * one, so the picker shows the call language's voices instead of one global list. MiniMax
 * does not publish a gender per voice, so these stay one list rather than carrying a guess
 * read off the English name (its own names disagree: News_Anchor is 新闻女声).
 *
 * Cloned and generated voices are not here — 获取音色 (`/v1/get_voice`) lists an account's own.
 */
export interface MinimaxVoice {
  id: string;
  name: string;
  gender?: "female" | "male";
}

export const MINIMAX_VOICES: Readonly<Record<string, readonly MinimaxVoice[]>> = {
  zh: [
    { id: "Chinese (Mandarin)_Crisp_Girl", name: "Crisp Girl" },
    { id: "Chinese (Mandarin)_Cute_Spirit", name: "Cute Spirit" },
    { id: "Chinese (Mandarin)_Gentle_Senior", name: "Gentle Senior" },
    { id: "Chinese (Mandarin)_Gentle_Youth", name: "Gentle Youth" },
    { id: "Chinese (Mandarin)_Gentleman", name: "Gentleman" },
    { id: "Chinese (Mandarin)_HK_Flight_Attendant", name: "HK Flight Attendant" },
    { id: "Chinese (Mandarin)_Humorous_Elder", name: "Humorous Elder" },
    { id: "Chinese (Mandarin)_Kind", name: "Kind" },
    { id: "Chinese (Mandarin)_Lyrical_Voice", name: "Lyrical Voice" },
    { id: "Chinese (Mandarin)_Male_Announcer", name: "Male Announcer" },
    { id: "Chinese (Mandarin)_Mature_Woman", name: "Mature Woman" },
    { id: "Chinese (Mandarin)_News_Anchor", name: "News Anchor" },
    { id: "Chinese (Mandarin)_Pure", name: "Pure" },
    { id: "Chinese (Mandarin)_Radio_Host", name: "Radio Host" },
    { id: "Chinese (Mandarin)_Reliable_Executive", name: "Reliable Executive" },
    { id: "Chinese (Mandarin)_Sincere_Adult", name: "Sincere Adult" },
    { id: "Chinese (Mandarin)_Soft_Girl", name: "Soft Girl" },
    { id: "Chinese (Mandarin)_Southern_Young_Man", name: "Southern Young Man" },
    { id: "Chinese (Mandarin)_Straightforward_Boy", name: "Straightforward Boy" },
    { id: "Chinese (Mandarin)_Stubborn_Friend", name: "Stubborn Friend" },
    { id: "Chinese (Mandarin)_Sweet_Lady", name: "Sweet Lady" },
    { id: "Chinese (Mandarin)_Unrestrained_Young_Man", name: "Unrestrained Young Man" },
    { id: "Chinese (Mandarin)_Warm_Bestie", name: "Warm Bestie" },
    { id: "Chinese (Mandarin)_Warm_Girl", name: "Warm Girl" },
    { id: "Chinese (Mandarin)_Wise_Women", name: "Wise Women" },
  ],
  yue: [
    { id: "Cantonese_CuteGirl", name: "Cute Girl" },
    { id: "Cantonese_GentleLady", name: "Gentle Lady" },
    { id: "Cantonese_KindWoman", name: "Kind Woman" },
    { id: "Cantonese_PlayfulMan", name: "Playful Man" },
    { id: "Cantonese_ProfessionalHost", name: "Professional Host" },
    { id: "Cantonese_podacast_host_1", name: "Podacast Host 1" },
  ],
  en: [
    { id: "English_Aussie_Bloke", name: "Aussie Bloke" },
    { id: "English_Diligent_Man", name: "Diligent Man" },
    { id: "English_Gentle", name: "Gentle" },
    { id: "English_Graceful_Lady", name: "Graceful Lady" },
    { id: "English_Insightful_Speaker", name: "Insightful Speaker" },
    { id: "English_Lucky_Robot", name: "Lucky Robot" },
    { id: "English_Persuasive_Man", name: "Persuasive Man" },
    { id: "English_Trustworthy_Man", name: "Trustworthy Man" },
    { id: "English_Whispering_girl", name: "Whispering Girl" },
    { id: "English_radiant_girl", name: "Radiant Girl" },
  ],
  ja: [
    { id: "Japanese_CalmLady", name: "Calm Lady" },
    { id: "Japanese_ColdQueen", name: "Cold Queen" },
    { id: "Japanese_DecisivePrincess", name: "Decisive Princess" },
    { id: "Japanese_DependableWoman", name: "Dependable Woman" },
    { id: "Japanese_DominantMan", name: "Dominant Man" },
    { id: "Japanese_GenerousIzakayaOwner", name: "Generous Izakaya Owner" },
    { id: "Japanese_GentleButler", name: "Gentle Butler" },
    { id: "Japanese_GracefulMaiden", name: "Graceful Maiden" },
    { id: "Japanese_InnocentBoy", name: "Innocent Boy" },
    { id: "Japanese_IntellectualSenior", name: "Intellectual Senior" },
    { id: "Japanese_KindLady", name: "Kind Lady" },
    { id: "Japanese_LoyalKnight", name: "Loyal Knight" },
    { id: "Japanese_OptimisticYouth", name: "Optimistic Youth" },
    { id: "Japanese_SeriousCommander", name: "Serious Commander" },
    { id: "Japanese_SportyStudent", name: "Sporty Student" },
    { id: "Japanese_Whisper_Belle", name: "Whisper Belle" },
  ],
  ko: [
    { id: "Korean_AirheadedGirl", name: "Airheaded Girl" },
    { id: "Korean_AthleticGirl", name: "Athletic Girl" },
    { id: "Korean_AthleticStudent", name: "Athletic Student" },
    { id: "Korean_BraveAdventurer", name: "Brave Adventurer" },
    { id: "Korean_BraveFemaleWarrior", name: "Brave Female Warrior" },
    { id: "Korean_BraveYouth", name: "Brave Youth" },
    { id: "Korean_CalmGentleman", name: "Calm Gentleman" },
    { id: "Korean_CalmLady", name: "Calm Lady" },
    { id: "Korean_CaringWoman", name: "Caring Woman" },
    { id: "Korean_CharmingElderSister", name: "Charming Elder Sister" },
    { id: "Korean_CharmingSister", name: "Charming Sister" },
    { id: "Korean_CheerfulBoyfriend", name: "Cheerful Boyfriend" },
    { id: "Korean_CheerfulCoolJunior", name: "Cheerful Cool Junior" },
    { id: "Korean_CheerfulLittleSister", name: "Cheerful Little Sister" },
    { id: "Korean_ChildhoodFriendGirl", name: "Childhood Friend Girl" },
    { id: "Korean_CockyGuy", name: "Cocky Guy" },
    { id: "Korean_ColdGirl", name: "Cold Girl" },
    { id: "Korean_ColdYoungMan", name: "Cold Young Man" },
    { id: "Korean_ConfidentBoss", name: "Confident Boss" },
    { id: "Korean_ConsiderateSenior", name: "Considerate Senior" },
    { id: "Korean_DecisiveQueen", name: "Decisive Queen" },
    { id: "Korean_DominantMan", name: "Dominant Man" },
    { id: "Korean_ElegantPrincess", name: "Elegant Princess" },
    { id: "Korean_EnchantingSister", name: "Enchanting Sister" },
    { id: "Korean_EnthusiasticTeen", name: "Enthusiastic Teen" },
    { id: "Korean_FriendlyBigSister", name: "Friendly Big Sister" },
    { id: "Korean_GentleBoss", name: "Gentle Boss" },
    { id: "Korean_GentleWoman", name: "Gentle Woman" },
    { id: "Korean_HaughtyLady", name: "Haughty Lady" },
    { id: "Korean_InnocentBoy", name: "Innocent Boy" },
    { id: "Korean_IntellectualMan", name: "Intellectual Man" },
    { id: "Korean_IntellectualSenior", name: "Intellectual Senior" },
    { id: "Korean_LonelyWarrior", name: "Lonely Warrior" },
    { id: "Korean_MatureLady", name: "Mature Lady" },
    { id: "Korean_MysteriousGirl", name: "Mysterious Girl" },
    { id: "Korean_OptimisticYouth", name: "Optimistic Youth" },
    { id: "Korean_PlayboyCharmer", name: "Playboy Charmer" },
    { id: "Korean_PossessiveMan", name: "Possessive Man" },
    { id: "Korean_QuirkyGirl", name: "Quirky Girl" },
    { id: "Korean_ReliableSister", name: "Reliable Sister" },
    { id: "Korean_ReliableYouth", name: "Reliable Youth" },
    { id: "Korean_SassyGirl", name: "Sassy Girl" },
    { id: "Korean_ShyGirl", name: "Shy Girl" },
    { id: "Korean_SoothingLady", name: "Soothing Lady" },
    { id: "Korean_StrictBoss", name: "Strict Boss" },
    { id: "Korean_SweetGirl", name: "Sweet Girl" },
    { id: "Korean_ThoughtfulWoman", name: "Thoughtful Woman" },
    { id: "Korean_WiseElf", name: "Wise Elf" },
    { id: "Korean_WiseTeacher", name: "Wise Teacher" },
  ],
  es: [
    { id: "Spanish_AngryMan", name: "Angry Man" },
    { id: "Spanish_AnimeCharacter", name: "Anime Character" },
    { id: "Spanish_Arnold", name: "Arnold" },
    { id: "Spanish_AssertiveQueen", name: "Assertive Queen" },
    { id: "Spanish_BossyLeader", name: "Bossy Leader" },
    { id: "Spanish_CaptivatingStoryteller", name: "Captivating Storyteller" },
    { id: "Spanish_CaringGirlfriend", name: "Caring Girlfriend" },
    { id: "Spanish_ChattyGirl", name: "Chatty Girl" },
    { id: "Spanish_Comedian", name: "Comedian" },
    { id: "Spanish_CompellingGirl", name: "Compelling Girl" },
    { id: "Spanish_ConfidentWoman", name: "Confident Woman" },
    { id: "Spanish_Debator", name: "Debator" },
    { id: "Spanish_Deep", name: "Deep" },
    { id: "Spanish_DeterminedManager", name: "Determined Manager" },
    { id: "Spanish_EnergeticBoy", name: "Energetic Boy" },
    { id: "Spanish_FrankLady", name: "Frank Lady" },
    { id: "Spanish_Fussyhostess", name: "Fussyhostess" },
    { id: "Spanish_Ghost", name: "Ghost" },
    { id: "Spanish_HumorousElder", name: "Humorous Elder" },
    { id: "Spanish_Intonategirl", name: "Intonategirl" },
    { id: "Spanish_Jovialman", name: "Jovialman" },
    { id: "Spanish_Kind", name: "Kind" },
    { id: "Spanish_MaturePartner", name: "Mature Partner" },
    { id: "Spanish_Narrator", name: "Narrator" },
    { id: "Spanish_PassionateWarrior", name: "Passionate Warrior" },
    { id: "Spanish_PowerfulSoldier", name: "Powerful Soldier" },
    { id: "Spanish_PowerfulVeteran", name: "Powerful Veteran" },
    { id: "Spanish_RationalMan", name: "Rational Man" },
    { id: "Spanish_ReliableMan", name: "Reliable Man" },
    { id: "Spanish_ReservedYoungMan", name: "Reserved Young Man" },
    { id: "Spanish_RomanticHusband", name: "Romantic Husband" },
    { id: "Spanish_Rudolph", name: "Rudolph" },
    { id: "Spanish_SantaClaus", name: "Santa Claus" },
    { id: "Spanish_SensibleManager", name: "Sensible Manager" },
    { id: "Spanish_SereneElder", name: "Serene Elder" },
    { id: "Spanish_SereneWoman", name: "Serene Woman" },
    { id: "Spanish_SincereTeen", name: "Sincere Teen" },
    { id: "Spanish_SophisticatedLady", name: "Sophisticated Lady" },
    { id: "Spanish_Steadymentor", name: "Steadymentor" },
    { id: "Spanish_StrictBoss", name: "Strict Boss" },
    { id: "Spanish_Strong", name: "Strong" },
    { id: "Spanish_ThoughtfulLady", name: "Thoughtful Lady" },
    { id: "Spanish_ThoughtfulMan", name: "Thoughtful Man" },
    { id: "Spanish_ToughBoss", name: "Tough Boss" },
    { id: "Spanish_WhimsicalGirl", name: "Whimsical Girl" },
    { id: "Spanish_WiseScholar", name: "Wise Scholar" },
    { id: "Spanish_Wiselady", name: "Wiselady" },
  ],
  pt: [
    { id: "Portuguese_AngryMan", name: "Angry Man" },
    { id: "Portuguese_AnimeCharacter", name: "Anime Character" },
    { id: "Portuguese_Arnold", name: "Arnold" },
    { id: "Portuguese_AssertiveQueen", name: "Assertive Queen" },
    { id: "Portuguese_AttractiveGirl", name: "Attractive Girl" },
    { id: "Portuguese_BossyLeader", name: "Bossy Leader" },
    { id: "Portuguese_CalmLeader", name: "Calm Leader" },
    { id: "Portuguese_CaptivatingStoryteller", name: "Captivating Storyteller" },
    { id: "Portuguese_CaringGirlfriend", name: "Caring Girlfriend" },
    { id: "Portuguese_CharmingLady", name: "Charming Lady" },
    { id: "Portuguese_CharmingQueen", name: "Charming Queen" },
    { id: "Portuguese_CharmingSanta", name: "Charming Santa" },
    { id: "Portuguese_ChattyGirl", name: "Chatty Girl" },
    { id: "Portuguese_Comedian", name: "Comedian" },
    { id: "Portuguese_CompellingGirl", name: "Compelling Girl" },
    { id: "Portuguese_ConfidentWoman", name: "Confident Woman" },
    { id: "Portuguese_Conscientiousinstructor", name: "Conscientiousinstructor" },
    { id: "Portuguese_Debator", name: "Debator" },
    { id: "Portuguese_Deep", name: "Deep" },
    { id: "Portuguese_DeterminedManager", name: "Determined Manager" },
    { id: "Portuguese_Dramatist", name: "Dramatist" },
    { id: "Portuguese_ElegantGirl", name: "Elegant Girl" },
    { id: "Portuguese_EnergeticBoy", name: "Energetic Boy" },
    { id: "Portuguese_FascinatingBoy", name: "Fascinating Boy" },
    { id: "Portuguese_FragileBoy", name: "Fragile Boy" },
    { id: "Portuguese_FrankLady", name: "Frank Lady" },
    { id: "Portuguese_FriendlyNeighbor", name: "Friendly Neighbor" },
    { id: "Portuguese_Fussyhostess", name: "Fussyhostess" },
    { id: "Portuguese_GentleTeacher", name: "Gentle Teacher" },
    { id: "Portuguese_Ghost", name: "Ghost" },
    { id: "Portuguese_Godfather", name: "Godfather" },
    { id: "Portuguese_GorgeousLady", name: "Gorgeous Lady" },
    { id: "Portuguese_GrimReaper", name: "Grim Reaper" },
    { id: "Portuguese_Grinch", name: "Grinch" },
    { id: "Portuguese_HumorousElder", name: "Humorous Elder" },
    { id: "Portuguese_InspiringLady", name: "Inspiring Lady" },
    { id: "Portuguese_Jovialman", name: "Jovialman" },
    { id: "Portuguese_Kind", name: "Kind" },
    { id: "Portuguese_LovelyLady", name: "Lovely Lady" },
    { id: "Portuguese_MaturePartner", name: "Mature Partner" },
    { id: "Portuguese_Narrator", name: "Narrator" },
    { id: "Portuguese_NaughtySchoolgirl", name: "Naughty Schoolgirl" },
    { id: "Portuguese_PassionateWarrior", name: "Passionate Warrior" },
    { id: "Portuguese_PlayfulGirl", name: "Playful Girl" },
    { id: "Portuguese_PlayfulSpirit", name: "Playful Spirit" },
    { id: "Portuguese_Pompouslady", name: "Pompouslady" },
    { id: "Portuguese_PowerfulSoldier", name: "Powerful Soldier" },
    { id: "Portuguese_PowerfulVeteran", name: "Powerful Veteran" },
    { id: "Portuguese_RationalMan", name: "Rational Man" },
    { id: "Portuguese_ReliableMan", name: "Reliable Man" },
    { id: "Portuguese_ReservedYoungMan", name: "Reserved Young Man" },
    { id: "Portuguese_RomanticHusband", name: "Romantic Husband" },
    { id: "Portuguese_Rudolph", name: "Rudolph" },
    { id: "Portuguese_SadTeen", name: "Sad Teen" },
    { id: "Portuguese_SantaClaus", name: "Santa Claus" },
    { id: "Portuguese_SensibleManager", name: "Sensible Manager" },
    { id: "Portuguese_SentimentalLady", name: "Sentimental Lady" },
    { id: "Portuguese_SereneElder", name: "Serene Elder" },
    { id: "Portuguese_SereneWoman", name: "Serene Woman" },
    { id: "Portuguese_SmartYoungGirl", name: "Smart Young Girl" },
    { id: "Portuguese_Steadymentor", name: "Steadymentor" },
    { id: "Portuguese_StressedLady", name: "Stressed Lady" },
    { id: "Portuguese_StrictBoss", name: "Strict Boss" },
    { id: "Portuguese_Strong", name: "Strong" },
    { id: "Portuguese_SweetGirl", name: "Sweet Girl" },
    { id: "Portuguese_TheatricalActor", name: "Theatrical Actor" },
    { id: "Portuguese_ThoughtfulLady", name: "Thoughtful Lady" },
    { id: "Portuguese_ThoughtfulMan", name: "Thoughtful Man" },
    { id: "Portuguese_ToughBoss", name: "Tough Boss" },
    { id: "Portuguese_UpsetGirl", name: "Upset Girl" },
    { id: "Portuguese_WhimsicalGirl", name: "Whimsical Girl" },
    { id: "Portuguese_WiseScholar", name: "Wise Scholar" },
    { id: "Portuguese_Wiselady", name: "Wiselady" },
  ],
  fr: [
    { id: "French_CasualMan", name: "Casual Man" },
    { id: "French_FemaleAnchor", name: "Female Anchor" },
    { id: "French_Female_News", name: "Female News" },
    { id: "French_MaleNarrator", name: "Male Narrator" },
    { id: "French_Male_Speech_New", name: "Male Speech New" },
    { id: "French_MovieLeadFemale", name: "Movie Lead Female" },
  ],
  de: [
    { id: "German_FriendlyMan", name: "Friendly Man" },
    { id: "German_PlayfulMan", name: "Playful Man" },
    { id: "German_SweetLady", name: "Sweet Lady" },
  ],
  it: [
    { id: "Italian_BraveHeroine", name: "Brave Heroine" },
    { id: "Italian_DiligentLeader", name: "Diligent Leader" },
    { id: "Italian_Narrator", name: "Narrator" },
    { id: "Italian_WanderingSorcerer", name: "Wandering Sorcerer" },
  ],
  ru: [
    { id: "Russian_AmbitiousWoman", name: "Ambitious Woman" },
    { id: "Russian_AttractiveGuy", name: "Attractive Guy" },
    { id: "Russian_Bad", name: "Bad" },
    { id: "Russian_BrightHeroine", name: "Bright Heroine" },
    { id: "Russian_CrazyQueen", name: "Crazy Queen" },
    { id: "Russian_HandsomeChildhoodFriend", name: "Handsome Childhood Friend" },
    { id: "Russian_PessimisticGirl", name: "Pessimistic Girl" },
    { id: "Russian_ReliableMan", name: "Reliable Man" },
  ],
  ar: [
    { id: "Arabic_CalmWoman", name: "Calm Woman" },
    { id: "Arabic_FriendlyGuy", name: "Friendly Guy" },
  ],
  id: [
    { id: "Indonesian_BossyLeader", name: "Bossy Leader" },
    { id: "Indonesian_CalmWoman", name: "Calm Woman" },
    { id: "Indonesian_CaringMan", name: "Caring Man" },
    { id: "Indonesian_CharmingGirl", name: "Charming Girl" },
    { id: "Indonesian_ConfidentWoman", name: "Confident Woman" },
    { id: "Indonesian_DeterminedBoy", name: "Determined Boy" },
    { id: "Indonesian_GentleGirl", name: "Gentle Girl" },
    { id: "Indonesian_ReservedYoungMan", name: "Reserved Young Man" },
    { id: "Indonesian_SweetGirl", name: "Sweet Girl" },
  ],
  vi: [{ id: "Vietnamese_kindhearted_girl", name: "Kindhearted Girl" }],
  th: [
    { id: "Thai_female_1_sample1", name: "Female 1 Sample1" },
    { id: "Thai_female_2_sample2", name: "Female 2 Sample2" },
    { id: "Thai_male_1_sample8", name: "Male 1 Sample8" },
    { id: "Thai_male_2_sample2", name: "Male 2 Sample2" },
  ],
  tr: [
    { id: "Turkish_CalmWoman", name: "Calm Woman" },
    { id: "Turkish_Trustworthyman", name: "Trustworthyman" },
  ],
  nl: [
    { id: "Dutch_bossy_leader", name: "Bossy Leader" },
    { id: "Dutch_kindhearted_girl", name: "Kindhearted Girl" },
  ],
};

/** The older short ids, Mandarin only; still accepted, and some accounts still use them. */
export const MINIMAX_LEGACY_ZH: readonly MinimaxVoice[] = [
  { id: "female-chengshu", name: "成熟女性", gender: "female" },
  { id: "female-shaonv", name: "少女", gender: "female" },
  { id: "female-tianmei", name: "甜美女性", gender: "female" },
  { id: "female-yujie", name: "御姐", gender: "female" },
  { id: "male-qn-badao", name: "霸道青年", gender: "male" },
  { id: "male-qn-daxuesheng", name: "青年大学生", gender: "male" },
  { id: "male-qn-jingying", name: "精英青年", gender: "male" },
  { id: "male-qn-qingse", name: "青涩青年", gender: "male" },
];
