// Generated from youtube-dubbing-extension (d30e0f1b) src/global/config/locale: AzureVoiceMap.ts,
// VoiceCodeLabelMap.ts, zhLanguageMap.ts and EnLanguageMap.ts — the plugin's target languages that
// have Azure voices, with the same voices per language. Left out: the :DragonHD* voices and
// zh-CN-XiaoxuanNeural (path B answers 400 / the voice is retired); voice ids use Azure's casing.

import type { Locale } from "../i18n/index.ts";

export interface AzureLanguage {
  /** The language in the UI languages, as the plugin's language picker names it. */
  name: Record<Locale, string>;
  female: string[];
  male: string[];
}

/** BCP 47 locale → its voices. */
export const AZURE_LANGUAGES: Record<string, AzureLanguage> = {
  "en-IE": {
    name: { zh: "爱尔兰(英语)", en: "Ireland(english)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ms-MY": {
    name: { zh: "马来西亚(马来语)", en: "Malaysia(Malay)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "en-IN": {
    name: { zh: "印度(英语)", en: "India(English)" },
    female: [
      "en-IN-AashiNeural",
      "en-IN-AnanyaNeural",
      "en-IN-KavyaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ta-IN": {
    name: { zh: "印度(泰米尔语)", en: "India(Tamil)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "el-GR": {
    name: { zh: "希腊", en: "Greece" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "nl-NL": {
    name: { zh: "荷兰", en: "Netherlands" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "zu-ZA": {
    name: { zh: "南非(祖鲁语)", en: "SA(Zulu)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "en-AU": {
    name: { zh: "澳大利亚", en: "Australia" },
    female: [
      "en-AU-AnnetteNeural",
      "en-AU-CarlyNeural",
      "en-AU-ElsieNeural",
      "en-AU-FreyaNeural",
      "en-AU-JoanneNeural",
      "en-AU-KimNeural",
      "en-AU-TinaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-AU-DarrenNeural",
      "en-AU-DuncanNeural",
      "en-AU-KenNeural",
      "en-AU-NeilNeural",
      "en-AU-TimNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "he-IL": {
    name: { zh: "以色列", en: "Israel" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "mk-MK": {
    name: { zh: "北马其顿", en: "North Macedonia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "hu-HU": {
    name: { zh: "匈牙利", en: "Hungary" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ml-IN": {
    name: { zh: "印度(马拉雅拉姆语)", en: "India(Malayalam)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fr-CA": {
    name: { zh: "加拿大(法语)", en: "Canada(French)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "fr-CA-ThierryNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "jv-ID": {
    name: { zh: "印度尼西亚(爪哇语)", en: "Indonesia(Javanese)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "pl-PL": {
    name: { zh: "波兰", en: "Poland" },
    female: [
      "pl-PL-AgnieszkaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "pt-PT": {
    name: { zh: "葡萄牙", en: "Portugal" },
    female: [
      "pt-PT-FernandaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ar-EG": {
    name: { zh: "埃及", en: "Egypt" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fr-BE": {
    name: { zh: "比利时(法语)", en: "Belgium(French)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ga-IE": {
    name: { zh: "爱尔兰(爱尔兰语)", en: "Ireland(Irish)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "cy-GB": {
    name: { zh: "英国(威尔士语)", en: "UK(Welsh)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fil-PH": {
    name: { zh: "菲律宾(菲律宾语)", en: "Philippines(Filipino)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "nb-NO": {
    name: { zh: "挪威", en: "Norway" },
    female: [
      "nb-NO-IselinNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "hr-HR": {
    name: { zh: "克罗地亚", en: "Croatia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "af-ZA": {
    name: { zh: "南非(阿非利卡语)", en: "SA(Afrikaans)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "gl-ES": {
    name: { zh: "西班牙(加利西亚语)", en: "Spain(Galician)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "de-AT": {
    name: { zh: "奥地利", en: "Austria" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "is-IS": {
    name: { zh: "冰岛", en: "Iceland" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "my-MM": {
    name: { zh: "缅甸", en: "Myanmar" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "bg-BG": {
    name: { zh: "保加利亚", en: "Bulgaria" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "cs-CZ": {
    name: { zh: "捷克", en: "Czech Republic" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "uz-UZ": {
    name: { zh: "乌兹别克斯坦", en: "Uzbekistan" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "zh-TW": {
    name: { zh: "中国台湾", en: "Taiwan" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "en-HK": {
    name: { zh: "中国香港(英语)", en: "HK(English)" },
    female: ["en-US-JennyMultilingualNeural"],
    male: ["en-US-RyanMultilingualNeural"],
  },
  "ko-KR": {
    name: { zh: "韩国", en: "South Korea" },
    female: [
      "ko-KR-JiMinNeural",
      "ko-KR-SeoHyeonNeural",
      "ko-KR-SoonBokNeural",
      "ko-KR-YuJinNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "ko-KR-BongJinNeural",
      "ko-KR-GookMinNeural",
      "ko-KR-HyunsuNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "sk-SK": {
    name: { zh: "斯洛伐克", en: "Slovakia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ps-AF": {
    name: { zh: "阿富汗", en: "Afghanistan" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ru-RU": {
    name: { zh: "俄罗斯", en: "Russia" },
    female: [
      "ru-RU-DariyaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "sq-AL": {
    name: { zh: "阿尔巴尼亚", en: "Albania" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "sv-SE": {
    name: { zh: "瑞典", en: "Sweden" },
    female: [
      "sv-SE-HilleviNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "am-ET": {
    name: { zh: "埃塞俄比亚", en: "Ethiopia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "da-DK": {
    name: { zh: "丹麦", en: "Denmark" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "mn-MN": {
    name: { zh: "蒙古", en: "Mongolia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "uk-UA": {
    name: { zh: "乌克兰", en: "Ukraine" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "en-US": {
    name: { zh: "美国(英语)", en: "US(English)" },
    female: [
      "en-US-JaneNeural",
      "en-US-SaraNeural",
      "en-US-NancyNeural",
      "en-US-AmberNeural",
      "en-US-AshleyNeural",
      "en-US-CoraNeural",
      "en-US-ElizabethNeural",
      "en-US-MonicaNeural",
      "en-US-AIGenerate2Neural",
      "en-US-BlueNeural",
      "en-US-JennyMultilingualNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-DavisNeural",
      "en-US-JasonNeural",
      "en-US-TonyNeural",
      "en-US-BrandonNeural",
      "en-US-JacobNeural",
      "en-US-AIGenerate1Neural",
      "en-US-BlueNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
    ],
  },
  "lv-LV": {
    name: { zh: "拉脱维亚", en: "Latvia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "nl-BE": {
    name: { zh: "比利时(荷兰语)", en: "Belgium(Dutch)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "zh-CN": {
    name: { zh: "中国", en: "China" },
    female: [
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
      "zh-CN-XiaohanNeural",
      "zh-CN-XiaomengNeural",
      "zh-CN-XiaomoNeural",
      "zh-CN-XiaoqiuNeural",
      "zh-CN-XiaoruiNeural",
      "zh-CN-XiaoshuangNeural",
      "zh-CN-XiaoyanNeural",
      "zh-CN-XiaoyouNeural",
      "zh-CN-XiaozhenNeural",
      "zh-CN-XiaorouNeural",
      "wuu-CN-XiaotongNeural",
      "yue-CN-XiaoMinNeural",
      "zh-CN-liaoning-XiaobeiNeural",
      "zh-CN-shaanxi-XiaoniNeural",
    ],
    male: [
      "zh-CN-YunyiMultilingualNeural",
      "zh-CN-YunfengNeural",
      "zh-CN-YunhaoNeural",
      "zh-CN-YunjieNeural",
      "zh-CN-YunyeNeural",
      "zh-CN-YunzeNeural",
      "wuu-CN-YunzheNeural",
      "yue-CN-YunSongNeural",
      "zh-CN-guangxi-YunqiNeural",
      "zh-CN-henan-YundengNeural",
      "zh-CN-liaoning-YunbiaoNeural",
      "zh-CN-shandong-YunxiangNeural",
      "zh-CN-sichuan-YunxiNeural",
    ],
  },
  "ur-PK": {
    name: { zh: "巴基斯坦", en: "Pakistan" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "te-IN": {
    name: { zh: "印度(泰卢固语)", en: "India(Telugu)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "hi-IN": {
    name: { zh: "印度(印地语)", en: "India(Hindi)" },
    female: [
      "hi-IN-AnanyaNeural",
      "hi-IN-KavyaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "de-CH": {
    name: { zh: "瑞士(德语)", en: "Switzerland(German)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ja-JP": {
    name: { zh: "日本", en: "Japan" },
    female: [
      "ja-JP-ShioriNeural",
      "ja-JP-MayuNeural",
      "ja-JP-AoiNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "ja-JP-NaokiNeural",
      "ja-JP-DaichiNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "bs-BA": {
    name: { zh: "波斯尼亚", en: "Bosnia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ne-NP": {
    name: { zh: "尼泊尔", en: "Nepal" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ka-GE": {
    name: { zh: "格鲁吉亚", en: "Georgia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fa-IR": {
    name: { zh: "伊朗", en: "Iran" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ro-RO": {
    name: { zh: "罗马尼亚", en: "Romania" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "mt-MT": {
    name: { zh: "马耳他", en: "Malta" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "et-EE": {
    name: { zh: "爱沙尼亚", en: "Estonia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "tr-TR": {
    name: { zh: "土耳其", en: "Turkey" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fr-FR": {
    name: { zh: "法国", en: "France" },
    female: [
      "fr-FR-JacquelineNeural",
      "fr-FR-JosephineNeural",
      "fr-FR-BrigitteNeural",
      "fr-FR-CoralieNeural",
      "fr-FR-CelesteNeural",
      "fr-FR-YvetteNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "fr-FR-ClaudeNeural",
      "fr-FR-AlainNeural",
      "fr-FR-JeromeNeural",
      "fr-FR-MauriceNeural",
      "fr-FR-YvesNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "vi-VN": {
    name: { zh: "越南", en: "Vietnam" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "en-GB": {
    name: { zh: "英国", en: "United Kingdom" },
    female: [
      "en-GB-AbbiNeural",
      "en-GB-BellaNeural",
      "en-GB-HollieNeural",
      "en-GB-OliviaNeural",
      "en-GB-MiaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-GB-AlfieNeural",
      "en-GB-ElliotNeural",
      "en-GB-EthanNeural",
      "en-GB-NoahNeural",
      "en-GB-OliverNeural",
      "en-US-RyanMultilingualNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "km-KH": {
    name: { zh: "柬埔寨", en: "Cambodia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fi-FI": {
    name: { zh: "芬兰", en: "Finland" },
    female: [
      "fi-FI-SelmaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "az-AZ": {
    name: { zh: "阿塞拜疆", en: "Azerbaijan" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "en-CA": {
    name: { zh: "加拿大(英语)", en: "Canada(English)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "lt-LT": {
    name: { zh: "立陶宛", en: "Lithuania" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "sl-SI": {
    name: { zh: "斯洛文尼亚", en: "Slovenia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "bn-IN": {
    name: { zh: "印度(孟加拉语)", en: "India(Bengali)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "si-LK": {
    name: { zh: "斯里兰卡(僧伽罗语)", en: "Sri Lanka(Sinhala)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "fr-CH": {
    name: { zh: "瑞士(法语)", en: "Switzerland(French)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "kn-IN": {
    name: { zh: "印度(卡纳达语)", en: "India(Kannada)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "lo-LA": {
    name: { zh: "老挝", en: "Laos" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ar-SA": {
    name: { zh: "沙特阿拉伯", en: "Saudi Arabia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "ca-ES": {
    name: { zh: "西班牙(加泰罗尼亚语)", en: "Spain(Catalan)" },
    female: [
      "ca-ES-AlbaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "de-DE": {
    name: { zh: "德国", en: "Germany" },
    female: [
      "de-DE-GiselaNeural",
      "de-DE-ElkeNeural",
      "de-DE-KlarissaNeural",
      "de-DE-LouisaNeural",
      "de-DE-MajaNeural",
      "de-DE-TanjaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "de-DE-BerndNeural",
      "de-DE-KasperNeural",
      "de-DE-ChristophNeural",
      "de-DE-KlausNeural",
      "de-DE-RalfNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "zh-HK": {
    name: { zh: "中国香港(中文)", en: "HK (Chinese)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "pt-BR": {
    name: { zh: "巴西", en: "Brazil" },
    female: [
      "pt-BR-GiovannaNeural",
      "pt-BR-LeilaNeural",
      "pt-BR-LeticiaNeural",
      "pt-BR-YaraNeural",
      "pt-BR-ManuelaNeural",
      "pt-BR-ThalitaNeural",
      "pt-BR-ElzaNeural",
      "pt-BR-BrendaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "pt-BR-JulioNeural",
      "pt-BR-HumbertoNeural",
      "pt-BR-NicolauNeural",
      "pt-BR-ValerioNeural",
      "pt-BR-FabioNeural",
      "pt-BR-DonatoNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "sr-RS": {
    name: { zh: "塞尔维亚", en: "Serbia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "sw-KE": {
    name: { zh: "肯尼亚(斯瓦希里语)", en: "Kenya" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "es-ES": {
    name: { zh: "西班牙(西班牙语)", en: "España(Spain)" },
    female: [
      "es-ES-AbrilNeural",
      "es-ES-EstrellaNeural",
      "es-ES-IreneNeural",
      "es-ES-LaiaNeural",
      "es-ES-LiaNeural",
      "es-ES-TrianaNeural",
      "es-ES-VeraNeural",
      "es-ES-XimenaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "es-ES-ArnauNeural",
      "es-ES-DarioNeural",
      "es-ES-EliasNeural",
      "es-ES-NilNeural",
      "es-ES-SaulNeural",
      "es-ES-TeoNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "kk-KZ": {
    name: { zh: "哈萨克斯坦", en: "Kazakhstan" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "so-SO": {
    name: { zh: "索马里", en: "Somalia" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "su-ID": {
    name: { zh: "印度尼西亚(巽他语)", en: "Indonesia(Sundanese)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "es-MX": {
    name: { zh: "墨西哥", en: "Mexico" },
    female: [
      "es-MX-BeatrizNeural",
      "es-MX-CandelaNeural",
      "es-MX-CarlotaNeural",
      "es-MX-LarissaNeural",
      "es-MX-MarinaNeural",
      "es-MX-NuriaNeural",
      "es-MX-RenataNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "es-MX-CecilioNeural",
      "es-MX-GerardoNeural",
      "es-MX-LibertoNeural",
      "es-MX-LucianoNeural",
      "es-MX-PelayoNeural",
      "es-MX-YagoNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "it-IT": {
    name: { zh: "意大利", en: "Italy" },
    female: [
      "it-IT-FabiolaNeural",
      "it-IT-FiammaNeural",
      "it-IT-ImeldaNeural",
      "it-IT-IrmaNeural",
      "it-IT-PalmiraNeural",
      "it-IT-PierinaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "it-IT-BenignoNeural",
      "it-IT-CalimeroNeural",
      "it-IT-CataldoNeural",
      "it-IT-GianniNeural",
      "it-IT-GiuseppeNeural",
      "it-IT-LisandroNeural",
      "it-IT-RinaldoNeural",
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "bn-BD": {
    name: { zh: "孟加拉", en: "Bangladesh" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "id-ID": {
    name: { zh: "印度尼西亚", en: "Indonesia(Indonesian)" },
    female: [
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
  "th-TH": {
    name: { zh: "泰国", en: "Thailand" },
    female: [
      "th-TH-AcharaNeural",
      "en-US-AvaMultilingualNeural",
      "en-US-EmmaMultilingualNeural",
      "de-DE-SeraphinaMultilingualNeural",
      "en-US-JennyMultilingualNeural",
      "fr-FR-VivienneMultilingualNeural",
      "zh-CN-XiaoxiaoMultilingualNeural",
      "zh-CN-XiaochenMultilingualNeural",
      "zh-CN-XiaoyuMultilingualNeural",
    ],
    male: [
      "en-US-AndrewMultilingualNeural",
      "en-US-BrianMultilingualNeural",
      "de-DE-FlorianMultilingualNeural",
      "en-US-RyanMultilingualNeural",
      "fr-FR-RemyMultilingualNeural",
      "ja-JP-MasaruMultilingualNeural",
      "zh-CN-YunyiMultilingualNeural",
    ],
  },
};

/** Voice id → the locale it belongs to, its name in that language and in English. */
export const AZURE_VOICE_NAMES: Record<string, { locale: string; local: string; display: string }> =
  {
    "en-US-AvaMultilingualNeural": {
      locale: "en-US",
      local: "Ava Multilingual",
      display: "Ava Multilingual",
    },
    "en-US-EmmaMultilingualNeural": {
      locale: "en-US",
      local: "Emma Multilingual",
      display: "Emma Multilingual",
    },
    "en-US-JennyMultilingualNeural": {
      locale: "en-US",
      local: "Jenny Multilingual",
      display: "Jenny Multilingual",
    },
    "de-DE-SeraphinaMultilingualNeural": {
      locale: "de-DE",
      local: "Seraphina Mehrsprachig",
      display: "Seraphina Multilingual",
    },
    "fr-FR-VivienneMultilingualNeural": {
      locale: "fr-FR",
      local: "Vivienne Multilingue",
      display: "Vivienne Multilingual",
    },
    "zh-CN-XiaoxiaoMultilingualNeural": {
      locale: "zh-CN",
      local: "晓晓 多语言",
      display: "Xiaoxiao Multilingual",
    },
    "zh-CN-XiaochenMultilingualNeural": {
      locale: "zh-CN",
      local: "晓辰 多语言",
      display: "Xiaochen Multilingual",
    },
    "zh-CN-XiaoyuMultilingualNeural": {
      locale: "zh-CN",
      local: "晓雨 多语言",
      display: "Xiaoyu Multilingual",
    },
    "en-US-AndrewMultilingualNeural": {
      locale: "en-US",
      local: "Andrew Multilingual",
      display: "Andrew Multilingual",
    },
    "en-US-BrianMultilingualNeural": {
      locale: "en-US",
      local: "Brian Multilingual",
      display: "Brian Multilingual",
    },
    "en-US-RyanMultilingualNeural": {
      locale: "en-US",
      local: "Ryan Multilingual",
      display: "Ryan Multilingual",
    },
    "de-DE-FlorianMultilingualNeural": {
      locale: "de-DE",
      local: "Florian Mehrsprachig",
      display: "Florian Multilingual",
    },
    "fr-FR-RemyMultilingualNeural": {
      locale: "fr-FR",
      local: "Rémy Multilingue",
      display: "Remy Multilingual",
    },
    "ja-JP-MasaruMultilingualNeural": {
      locale: "ja-JP",
      local: "勝 多言語",
      display: "Masaru Multilingual",
    },
    "zh-CN-YunyiMultilingualNeural": {
      locale: "zh-CN",
      local: "云逸 多语言",
      display: "Yunyi Multilingual",
    },
    "en-IN-AashiNeural": { locale: "en-IN", local: "Aashi", display: "Aashi" },
    "en-IN-AnanyaNeural": { locale: "en-IN", local: "Ananya", display: "Ananya" },
    "en-IN-KavyaNeural": { locale: "en-IN", local: "Kavya", display: "Kavya" },
    "en-AU-AnnetteNeural": { locale: "en-AU", local: "Annette", display: "Annette" },
    "en-AU-CarlyNeural": { locale: "en-AU", local: "Carly", display: "Carly" },
    "en-AU-ElsieNeural": { locale: "en-AU", local: "Elsie", display: "Elsie" },
    "en-AU-FreyaNeural": { locale: "en-AU", local: "Freya", display: "Freya" },
    "en-AU-JoanneNeural": { locale: "en-AU", local: "Joanne", display: "Joanne" },
    "en-AU-KimNeural": { locale: "en-AU", local: "Kim", display: "Kim" },
    "en-AU-TinaNeural": { locale: "en-AU", local: "Tina", display: "Tina" },
    "en-AU-DarrenNeural": { locale: "en-AU", local: "Darren", display: "Darren" },
    "en-AU-DuncanNeural": { locale: "en-AU", local: "Duncan", display: "Duncan" },
    "en-AU-KenNeural": { locale: "en-AU", local: "Ken", display: "Ken" },
    "en-AU-NeilNeural": { locale: "en-AU", local: "Neil", display: "Neil" },
    "en-AU-TimNeural": { locale: "en-AU", local: "Tim", display: "Tim" },
    "fr-CA-ThierryNeural": { locale: "fr-CA", local: "Thierry", display: "Thierry" },
    "pl-PL-AgnieszkaNeural": { locale: "pl-PL", local: "Agnieszka", display: "Agnieszka" },
    "pt-PT-FernandaNeural": { locale: "pt-PT", local: "Fernanda", display: "Fernanda" },
    "nb-NO-IselinNeural": { locale: "nb-NO", local: "Iselin", display: "Iselin" },
    "ko-KR-JiMinNeural": { locale: "ko-KR", local: "지민", display: "JiMin" },
    "ko-KR-SeoHyeonNeural": { locale: "ko-KR", local: "서현", display: "SeoHyeon" },
    "ko-KR-SoonBokNeural": { locale: "ko-KR", local: "순복", display: "SoonBok" },
    "ko-KR-YuJinNeural": { locale: "ko-KR", local: "유진", display: "YuJin" },
    "ko-KR-BongJinNeural": { locale: "ko-KR", local: "봉진", display: "BongJin" },
    "ko-KR-GookMinNeural": { locale: "ko-KR", local: "국민", display: "GookMin" },
    "ko-KR-HyunsuNeural": { locale: "ko-KR", local: "현수", display: "Hyunsu" },
    "ru-RU-DariyaNeural": { locale: "ru-RU", local: "Дария", display: "Dariya" },
    "sv-SE-HilleviNeural": { locale: "sv-SE", local: "Hillevi", display: "Hillevi" },
    "en-US-JaneNeural": { locale: "en-US", local: "Jane", display: "Jane" },
    "en-US-SaraNeural": { locale: "en-US", local: "Sara", display: "Sara" },
    "en-US-NancyNeural": { locale: "en-US", local: "Nancy", display: "Nancy" },
    "en-US-AmberNeural": { locale: "en-US", local: "Amber", display: "Amber" },
    "en-US-AshleyNeural": { locale: "en-US", local: "Ashley", display: "Ashley" },
    "en-US-CoraNeural": { locale: "en-US", local: "Cora", display: "Cora" },
    "en-US-ElizabethNeural": { locale: "en-US", local: "Elizabeth", display: "Elizabeth" },
    "en-US-MonicaNeural": { locale: "en-US", local: "Monica", display: "Monica" },
    "en-US-AIGenerate2Neural": { locale: "en-US", local: "AIGenerate2", display: "AIGenerate2" },
    "en-US-BlueNeural": { locale: "en-US", local: "Blue", display: "Blue" },
    "en-US-DavisNeural": { locale: "en-US", local: "Davis", display: "Davis" },
    "en-US-JasonNeural": { locale: "en-US", local: "Jason", display: "Jason" },
    "en-US-TonyNeural": { locale: "en-US", local: "Tony", display: "Tony" },
    "en-US-BrandonNeural": { locale: "en-US", local: "Brandon", display: "Brandon" },
    "en-US-JacobNeural": { locale: "en-US", local: "Jacob", display: "Jacob" },
    "en-US-AIGenerate1Neural": { locale: "en-US", local: "AIGenerate1", display: "AIGenerate1" },
    "zh-CN-XiaohanNeural": { locale: "zh-CN", local: "晓涵", display: "Xiaohan" },
    "zh-CN-XiaomengNeural": { locale: "zh-CN", local: "晓梦", display: "Xiaomeng" },
    "zh-CN-XiaomoNeural": { locale: "zh-CN", local: "晓莫", display: "Xiaomo" },
    "zh-CN-XiaoqiuNeural": { locale: "zh-CN", local: "晓秋", display: "Xiaoqiu" },
    "zh-CN-XiaoruiNeural": { locale: "zh-CN", local: "晓睿", display: "Xiaorui" },
    "zh-CN-XiaoshuangNeural": { locale: "zh-CN", local: "晓双", display: "Xiaoshuang" },
    "zh-CN-XiaoyanNeural": { locale: "zh-CN", local: "晓颜", display: "Xiaoyan" },
    "zh-CN-XiaoyouNeural": { locale: "zh-CN", local: "晓悠", display: "Xiaoyou" },
    "zh-CN-XiaozhenNeural": { locale: "zh-CN", local: "晓甄", display: "Xiaozhen" },
    "zh-CN-XiaorouNeural": { locale: "zh-CN", local: "晓柔", display: "Xiaorou" },
    "wuu-CN-XiaotongNeural": { locale: "zh-CN", local: "晓彤", display: "Xiaotong" },
    "yue-CN-XiaoMinNeural": { locale: "zh-CN", local: "晓敏", display: "XiaoMin" },
    "zh-CN-liaoning-XiaobeiNeural": { locale: "zh-CN", local: "晓北 辽宁", display: "Xiaobei" },
    "zh-CN-shaanxi-XiaoniNeural": { locale: "zh-CN", local: "晓妮 陕西", display: "Xiaoni" },
    "zh-CN-YunfengNeural": { locale: "zh-CN", local: "云枫", display: "Yunfeng" },
    "zh-CN-YunhaoNeural": { locale: "zh-CN", local: "云皓", display: "Yunhao" },
    "zh-CN-YunjieNeural": { locale: "zh-CN", local: "云杰", display: "Yunjie" },
    "zh-CN-YunyeNeural": { locale: "zh-CN", local: "云野", display: "Yunye" },
    "zh-CN-YunzeNeural": { locale: "zh-CN", local: "云泽", display: "Yunze" },
    "wuu-CN-YunzheNeural": { locale: "zh-CN", local: "云哲", display: "Yunzhe" },
    "yue-CN-YunSongNeural": { locale: "zh-CN", local: "云松", display: "YunSong" },
    "zh-CN-guangxi-YunqiNeural": { locale: "zh-CN", local: "云奇 广西", display: "Yunqi" },
    "zh-CN-henan-YundengNeural": { locale: "zh-CN", local: "云登 河南", display: "Yundeng" },
    "zh-CN-liaoning-YunbiaoNeural": { locale: "zh-CN", local: "云彪 辽宁", display: "Yunbiao" },
    "zh-CN-shandong-YunxiangNeural": { locale: "zh-CN", local: "云翔 山东", display: "Yunxiang" },
    "zh-CN-sichuan-YunxiNeural": { locale: "zh-CN", local: "云希 四川", display: "Yunxi" },
    "hi-IN-AnanyaNeural": { locale: "hi-IN", local: "अनन्या", display: "Ananya" },
    "hi-IN-KavyaNeural": { locale: "hi-IN", local: "काव्या", display: "Kavya" },
    "ja-JP-ShioriNeural": { locale: "ja-JP", local: "志織", display: "Shiori" },
    "ja-JP-MayuNeural": { locale: "ja-JP", local: "真夕", display: "Mayu" },
    "ja-JP-AoiNeural": { locale: "ja-JP", local: "碧衣", display: "Aoi" },
    "ja-JP-NaokiNeural": { locale: "ja-JP", local: "直紀", display: "Naoki" },
    "ja-JP-DaichiNeural": { locale: "ja-JP", local: "大智", display: "Daichi" },
    "fr-FR-JacquelineNeural": { locale: "fr-FR", local: "Jacqueline", display: "Jacqueline" },
    "fr-FR-JosephineNeural": { locale: "fr-FR", local: "Josephine", display: "Josephine" },
    "fr-FR-BrigitteNeural": { locale: "fr-FR", local: "Brigitte", display: "Brigitte" },
    "fr-FR-CoralieNeural": { locale: "fr-FR", local: "Coralie", display: "Coralie" },
    "fr-FR-CelesteNeural": { locale: "fr-FR", local: "Celeste", display: "Celeste" },
    "fr-FR-YvetteNeural": { locale: "fr-FR", local: "Yvette", display: "Yvette" },
    "fr-FR-ClaudeNeural": { locale: "fr-FR", local: "Claude", display: "Claude" },
    "fr-FR-AlainNeural": { locale: "fr-FR", local: "Alain", display: "Alain" },
    "fr-FR-JeromeNeural": { locale: "fr-FR", local: "Jerome", display: "Jerome" },
    "fr-FR-MauriceNeural": { locale: "fr-FR", local: "Maurice", display: "Maurice" },
    "fr-FR-YvesNeural": { locale: "fr-FR", local: "Yves", display: "Yves" },
    "en-GB-AbbiNeural": { locale: "en-GB", local: "Abbi", display: "Abbi" },
    "en-GB-BellaNeural": { locale: "en-GB", local: "Bella", display: "Bella" },
    "en-GB-HollieNeural": { locale: "en-GB", local: "Hollie", display: "Hollie" },
    "en-GB-OliviaNeural": { locale: "en-GB", local: "Olivia", display: "Olivia" },
    "en-GB-MiaNeural": { locale: "en-GB", local: "Mia", display: "Mia" },
    "en-GB-AlfieNeural": { locale: "en-GB", local: "Alfie", display: "Alfie" },
    "en-GB-ElliotNeural": { locale: "en-GB", local: "Elliot", display: "Elliot" },
    "en-GB-EthanNeural": { locale: "en-GB", local: "Ethan", display: "Ethan" },
    "en-GB-NoahNeural": { locale: "en-GB", local: "Noah", display: "Noah" },
    "en-GB-OliverNeural": { locale: "en-GB", local: "Oliver", display: "Oliver" },
    "fi-FI-SelmaNeural": { locale: "fi-FI", local: "Selma", display: "Selma" },
    "ca-ES-AlbaNeural": { locale: "ca-ES", local: "Alba", display: "Alba" },
    "de-DE-GiselaNeural": { locale: "de-DE", local: "Gisela", display: "Gisela" },
    "de-DE-ElkeNeural": { locale: "de-DE", local: "Elke", display: "Elke" },
    "de-DE-KlarissaNeural": { locale: "de-DE", local: "Klarissa", display: "Klarissa" },
    "de-DE-LouisaNeural": { locale: "de-DE", local: "Louisa", display: "Louisa" },
    "de-DE-MajaNeural": { locale: "de-DE", local: "Maja", display: "Maja" },
    "de-DE-TanjaNeural": { locale: "de-DE", local: "Tanja", display: "Tanja" },
    "de-DE-BerndNeural": { locale: "de-DE", local: "Bernd", display: "Bernd" },
    "de-DE-KasperNeural": { locale: "de-DE", local: "Kasper", display: "Kasper" },
    "de-DE-ChristophNeural": { locale: "de-DE", local: "Christoph", display: "Christoph" },
    "de-DE-KlausNeural": { locale: "de-DE", local: "Klaus", display: "Klaus" },
    "de-DE-RalfNeural": { locale: "de-DE", local: "Ralf", display: "Ralf" },
    "pt-BR-GiovannaNeural": { locale: "pt-BR", local: "Giovanna", display: "Giovanna" },
    "pt-BR-LeilaNeural": { locale: "pt-BR", local: "Leila", display: "Leila" },
    "pt-BR-LeticiaNeural": { locale: "pt-BR", local: "Leticia", display: "Leticia" },
    "pt-BR-YaraNeural": { locale: "pt-BR", local: "Yara", display: "Yara" },
    "pt-BR-ManuelaNeural": { locale: "pt-BR", local: "Manuela", display: "Manuela" },
    "pt-BR-ThalitaNeural": { locale: "pt-BR", local: "Thalita", display: "Thalita" },
    "pt-BR-ElzaNeural": { locale: "pt-BR", local: "Elza", display: "Elza" },
    "pt-BR-BrendaNeural": { locale: "pt-BR", local: "Brenda", display: "Brenda" },
    "pt-BR-JulioNeural": { locale: "pt-BR", local: "Julio", display: "Julio" },
    "pt-BR-HumbertoNeural": { locale: "pt-BR", local: "Humberto", display: "Humberto" },
    "pt-BR-NicolauNeural": { locale: "pt-BR", local: "Nicolau", display: "Nicolau" },
    "pt-BR-ValerioNeural": { locale: "pt-BR", local: "Valerio", display: "Valerio" },
    "pt-BR-FabioNeural": { locale: "pt-BR", local: "Fabio", display: "Fabio" },
    "pt-BR-DonatoNeural": { locale: "pt-BR", local: "Donato", display: "Donato" },
    "es-ES-AbrilNeural": { locale: "es-ES", local: "Abril", display: "Abril" },
    "es-ES-EstrellaNeural": { locale: "es-ES", local: "Estrella", display: "Estrella" },
    "es-ES-IreneNeural": { locale: "es-ES", local: "Irene", display: "Irene" },
    "es-ES-LaiaNeural": { locale: "es-ES", local: "Laia", display: "Laia" },
    "es-ES-LiaNeural": { locale: "es-ES", local: "Lia", display: "Lia" },
    "es-ES-TrianaNeural": { locale: "es-ES", local: "Triana", display: "Triana" },
    "es-ES-VeraNeural": { locale: "es-ES", local: "Vera", display: "Vera" },
    "es-ES-XimenaNeural": { locale: "es-ES", local: "Ximena", display: "Ximena" },
    "es-ES-ArnauNeural": { locale: "es-ES", local: "Arnau", display: "Arnau" },
    "es-ES-DarioNeural": { locale: "es-ES", local: "Dario", display: "Dario" },
    "es-ES-EliasNeural": { locale: "es-ES", local: "Elias", display: "Elias" },
    "es-ES-NilNeural": { locale: "es-ES", local: "Nil", display: "Nil" },
    "es-ES-SaulNeural": { locale: "es-ES", local: "Saul", display: "Saul" },
    "es-ES-TeoNeural": { locale: "es-ES", local: "Teo", display: "Teo" },
    "es-MX-BeatrizNeural": { locale: "es-MX", local: "Beatriz", display: "Beatriz" },
    "es-MX-CandelaNeural": { locale: "es-MX", local: "Candela", display: "Candela" },
    "es-MX-CarlotaNeural": { locale: "es-MX", local: "Carlota", display: "Carlota" },
    "es-MX-LarissaNeural": { locale: "es-MX", local: "Larissa", display: "Larissa" },
    "es-MX-MarinaNeural": { locale: "es-MX", local: "Marina", display: "Marina" },
    "es-MX-NuriaNeural": { locale: "es-MX", local: "Nuria", display: "Nuria" },
    "es-MX-RenataNeural": { locale: "es-MX", local: "Renata", display: "Renata" },
    "es-MX-CecilioNeural": { locale: "es-MX", local: "Cecilio", display: "Cecilio" },
    "es-MX-GerardoNeural": { locale: "es-MX", local: "Gerardo", display: "Gerardo" },
    "es-MX-LibertoNeural": { locale: "es-MX", local: "Liberto", display: "Liberto" },
    "es-MX-LucianoNeural": { locale: "es-MX", local: "Luciano", display: "Luciano" },
    "es-MX-PelayoNeural": { locale: "es-MX", local: "Pelayo", display: "Pelayo" },
    "es-MX-YagoNeural": { locale: "es-MX", local: "Yago", display: "Yago" },
    "it-IT-FabiolaNeural": { locale: "it-IT", local: "Fabiola", display: "Fabiola" },
    "it-IT-FiammaNeural": { locale: "it-IT", local: "Fiamma", display: "Fiamma" },
    "it-IT-ImeldaNeural": { locale: "it-IT", local: "Imelda", display: "Imelda" },
    "it-IT-IrmaNeural": { locale: "it-IT", local: "Irma", display: "Irma" },
    "it-IT-PalmiraNeural": { locale: "it-IT", local: "Palmira", display: "Palmira" },
    "it-IT-PierinaNeural": { locale: "it-IT", local: "Pierina", display: "Pierina" },
    "it-IT-BenignoNeural": { locale: "it-IT", local: "Benigno", display: "Benigno" },
    "it-IT-CalimeroNeural": { locale: "it-IT", local: "Calimero", display: "Calimero" },
    "it-IT-CataldoNeural": { locale: "it-IT", local: "Cataldo", display: "Cataldo" },
    "it-IT-GianniNeural": { locale: "it-IT", local: "Gianni", display: "Gianni" },
    "it-IT-GiuseppeNeural": { locale: "it-IT", local: "Giuseppe", display: "Giuseppe" },
    "it-IT-LisandroNeural": { locale: "it-IT", local: "Lisandro", display: "Lisandro" },
    "it-IT-RinaldoNeural": { locale: "it-IT", local: "Rinaldo", display: "Rinaldo" },
    "th-TH-AcharaNeural": { locale: "th-TH", local: "อัจฉรา", display: "Achara" },
  };
